# Generated by Django 4.1.1 on 2023-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscricoesMoodleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosdoaluno',
            name='cidade_prefeitura',
            field=models.CharField(choices=[('Cubatão', 'Cubatão'), ('Franco da Rocha', 'Franco da Rocha')], default='Cubatão', max_length=16, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
