# Generated by Django 4.1.1 on 2023-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscricoesMoodleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='nome',
            field=models.CharField(help_text='Em caso de nome social, é necessário que o mesmo conste em documento emitido pela \n            Receita Federal ou Instituto de Identificação para emissão do certificado de conclusão/participação com nome social.\n            Em caso de dúvidas, procure os canais de atendimento da Receita Federal. \n        ', max_length=63, verbose_name='Nome'),
        ),
    ]
