# Generated by Django 4.1.1 on 2023-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscricoesMoodleApp', '0002_curso_vagas_alter_dadosdoaluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_fim',
            field=models.DateTimeField(verbose_name='Fim das Atividades'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Início das Atividades'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(verbose_name='Número de Vagas'),
        ),
    ]
