# Generated by Django 4.1.1 on 2023-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscricoesMoodleApp', '0003_alter_curso_data_fim_alter_curso_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosdoaluno',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('W', 'Aguardando Avaliação')], default='W', max_length=1),
        ),
    ]
